### PR TITLE
News performance

### PR DESCRIPTION
**Pull request by stefan-mueller**
- Adds article for "news" section on comparison of **quanteda**, **tidytext** and **tm**
- I wrote text, updated the design of the plots, ran all analyses and saved the data frames with the performance as one .Rdata file.
- In the `.rmarkown` file (this file format, not `.Rmd`, seems to be necessary for blowdown/Hugo – I followed the design of http://tutorials.quanteda.io) I load the .Rdata file with `echo = FALSE` to avoid running the analysis every time the website is built.

### CODE REVIEW

**Comment by stefan-mueller** [comment]
I checked the [preview of the "news" page](https://deploy-preview-16--quanteda.netlify.com/news/) after making the PR. The article is shown there (incl. authors and first paragraph), but once I click on "Continue Reading" I get the "Error 404" message. @koheiw, could you have a look what needs to be changed?

**Comment by koheiw** [comment]
@stefan-mueller  please see https://deploy-preview-16--quanteda.netlify.com/performance/
I found the best plot for **microbenchmark**. I am not sure if we should mention how fast in concrete numbers, because they change machine to machine. I have been trying to use `cache = TRUE` but not yet working...

**Comment by stefan-mueller** [comment]
I made small changes and removed the old files. @koheiw, you will need to rerun the Rmarkdown file. I also added a new icon for the performance page. If you think that's not necessary, we need to place the link to the article somewhere else on the landing page.

**Review by koheiw — APPROVED** [review]
I think this is OK to be online, but let keep this hidden to give @kbenoit a chance to check.

**Pull request merged**
