### PR TITLE
Add qi logo

### PR DESCRIPTION
**Pull request by koheiw**
- Change the design to feature QI, keeping the function as landing page for **quanteda**
- Add QI logo and explain what the company is for in the About page 
- Add Tel Aviv University to users

### CODE REVIEW

**Comment by koheiw** [comment]
@kbenoit please add more to About page.

**Review by kbenoit — COMMENTED** [review]
What's the easiest way to preview the web page for a PR on the Hugo site?

**Comment by koheiw** [comment]
Please click 'Details' for netlify in 'Show all checks'.

**Comment by kbenoit** [comment]
@koheiw can you be more specific? When I build website locally (in RStudio) it does not show images.

**Comment by koheiw** [comment]
If you want to review online, please visit https://deploy-preview-14--quanteda.netlify.com/. If you want to preview locally, `blogdown::serve_site()` will show you the website.

**Review by kbenoit — APPROVED** [review]
Looks fine, although does not solve #13 and #6 yet. We can do that later as part of a QI website reorg though.

**Pull request merged**
